import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AddProductButton } from '@/app/Components/AddProductButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lazapee',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='navbar bg-base-100'>
          <div className='navbar-start'>
            <div className='dropdown'>
              <div
                tabIndex={0}
                role='button'
                className='btn btn-ghost lg:hidden'
              >
                <svg
                  xmlns='http://www.w3.org/2000/svg'
                  className='h-5 w-5'
                  fill='none'
                  viewBox='0 0 24 24'
                  stroke='currentColor'
                >
                  <path
                    strokeLinecap='round'
                    strokeLinejoin='round'
                    strokeWidth='2'
                    d='M4 6h16M4 12h8m-8 6h16'
                  />
                </svg>
              </div>
            </div>
            <a className='btn btn-ghost text-xl' href='/'>
              Lazapee
            </a>
          </div>
          <div className='navbar-end'>
            <AddProductButton className='mt-10' name='New Product' />
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
